### PR TITLE
Add Issuetemplate

### LINKED ISSUE #30: Set up issue templates

### PR DESCRIPTION
**Pull request by MaxHillebrand**
Closes #30

Added Bug Reports and Feature Requests.

Notice that you can add links to an external website in `Issue` UI by adding a `config.yml`. 
But since there is no documentation etc, maybe it's not needed.

### CODE REVIEW

**Comment by Kixunil** [comment]
FYI there also exist issue forms (beta GitHub feature).

**Comment by MaxHillebrand** [comment]
@Kixunil what do you mean? This config file like https://github.com/zkSNACKs/WalletWasabi/blob/master/.github/ISSUE_TEMPLATE/config.yml?

**Comment by Kixunil** [comment]
No, this: https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/blob/master/.github/ISSUE_TEMPLATE/test-forms.yml

You can see the result here: https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/issues/new?assignees=&labels=enhancement%2Csome+really+cool+shit&template=test-forms.yml&title=%5BTest%5D%3A+

**Comment by mwalbeck** [comment]
Issue forms look pretty cool, but I'll just stick with standard templates for now until I've had time to look more into issue forms.

Thanks, Max!

**Pull request merged**
